### ISSUE TITLE
Not working on YT TV

### ISSUE THREAD

**Issue by Nick2bad4u** [polywock/pipUnblocker#10]
No longer working on YT TV

**Comment by polywock** [comment]
I'm looking at the Web Store dashboard and there doesn't seem to be any spike in uninstalls. The issue is likely only affecting you. Try updating to the newest version (I published today). I migrated to MV3, which is required for all extensions by May 2024 deadline. Hopefully the update fixes the issue.

**Comment by Nick2bad4u** [comment]
> I'm looking at the Web Store dashboard and there doesn't seem to be any spike in uninstalls. The issue is likely only affecting you. Try updating to the newest version (I published today). I migrated to MV3, which is required for all extensions by May 2024 deadline. Hopefully the update fixes the issue.

Im using the edge install, so Ill have to wait and see if it fixes it once edge store updates

**Comment by polywock** [comment]
Edge usually takes a week to update for context. Here's steps to load it manually if needed. 

1. Go to https://github.com/polywock/pipUnblocker 
2. Press the green Code button and then Download zip. 
3. Extract the zip once download. 
4. Open Edge extensions page.  -> edge://extensions
5. Enable Developer mode on left side. 
6. Press Load unpacked and select the extracted folder.

**Comment by polywock** [comment]
@Nick2bad4u The Edge update is now live. Let me know if the problem still persists.

**Comment by Nick2bad4u** [comment]
> @Nick2bad4u The Edge update is now live. Let me know if the problem still persists.

If it's supposed to pop-up like regular YouTube. still nothing. Anything I can do to pull errors or logs for you?
I also tried the chrome version just to be sure and make sure the edge version was up to date.

**Comment by polywock** [comment]
> Anything I can do to pull errors or logs for you?

Yes, thank you. 

1. While on Youtube TV with video loaded, right click the page and click "Inspect" to open the developer tools. 
2. Open the console tab. 
3. Enter document.featurePolicy.allowsFeature('picture-in-picture')

If the extension is working, it should return true.

**Comment by polywock** [comment]
I should also mention that in MV2, only one extension could modify headers. If that's also that case for MV3 (I'm not sure), then the problem could be another extension is getting there first.

**Comment by Nick2bad4u** [comment]
> I should also mention that in MV2, only one extension could modify headers. If that's also that case for MV3 (I'm not sure), then the problem could be another extension is getting there first.

[Console returns True](https://gyazo.com/97cdc4a52bf347ef4b71beba9f924290)

returns as true. Hmm... I wonder what other extension could be interferring.. hmm

**Comment by polywock** [comment]
>  Console returns True... I wonder what other extension could be interferring... 

In that case, the extension is working with no interference. There could be a different reason why PiP isn't working. 

There are multiple techniques to disable PiP. Youtube TV might now be using the attribute approach. You can try this userscript (I made this years ago). Refresh your YT-TV page after adding. 

Clears 'disablePictureInPicture attribute when you play or pause the video. Make sure to pause before attempting to enter PiP. 

https://greasyfork.org/en/scripts/426660-remove-pip-disable-attributes

**Comment by Nick2bad4u** [comment]
> > Console returns True... I wonder what other extension could be interferring...
> 
> In that case, the extension is working with no interference. There could be a different reason why PiP isn't working.
> 
> There are multiple techniques to disable PiP. Youtube TV might now be using the attribute approach. You can try this userscript (I made this years ago). Refresh your YT-TV page after adding.
> 
> Clears 'disablePictureInPicture attribute when you play or pause the video. Make sure to pause before attempting to enter PiP.
> 
> https://greasyfork.org/en/scripts/426660-remove-pip-disable-attributes

No dice, but I did manage to find an extension: https://chromewebstore.google.com/detail/pip-for-youtube-tv/mlligheoamjjgchfnganmllkaijdkbmd that works.

You activate it via clicking the extension. Heres my current thought, I could be off track. But maybe PiP is enabled, BUT YoutubeTV is hiding the actual PiP button when you mouse over a video so you cant activate it. Does that sound plausible?

**Comment by polywock** [comment]
Thanks for the helping me understand the issue. That extension is pretty much just the "PiP extension by Google" with 3M users, which just toggles PiP mode. A few years back, Youtube TV was blocking PiP through a permission header. If that extension works, that means they're no longer doing that, at least for Edge. 

To improve my extension, I implemented a basic PiP functionality in the latest version. The Chrome version is live, but might take some time to get approved for Edge. When you click on it, it will toggle PiP. Not only that, it will also remove any disablePictureInPicture attributes (merging my userscript into the extension). 

So new version should remove feature-policy headers, permissions policy headers, the disablePictureInPicture attribute, and allow for basic PiP toggle. Hopefully that takes care of most use cases.

**Comment by Nick2bad4u** [comment]
> Thanks for the helping me understand the issue. That extension is pretty much just the "PiP extension by Google" with 3M users, which just toggles PiP mode. A few years back, Youtube TV was blocking PiP through a permission header. If that extension works, that means they're no longer doing that, at least for Edge. 
> 
> To improve my extension, I implemented a basic PiP functionality in the latest version. The Chrome version is live, but might take some time to get approved for Edge. When you click on it, it will toggle PiP. Not only that, it will also remove any disablePictureInPicture attributes (merging my userscript into the extension). 
> 
> So new version should remove feature-policy headers, permissions policy headers, the disablePictureInPicture attribute, and allow for basic PiP toggle. Hopefully that takes care of most use cases. 

Beautiful. I'll let you know how it works when it's live on edge!

**Comment by Nick2bad4u** [comment]
> > Thanks for the helping me understand the issue. That extension is pretty much just the "PiP extension by Google" with 3M users, which just toggles PiP mode. A few years back, Youtube TV was blocking PiP through a permission header. If that extension works, that means they're no longer doing that, at least for Edge.
> > To improve my extension, I implemented a basic PiP functionality in the latest version. The Chrome version is live, but might take some time to get approved for Edge. When you click on it, it will toggle PiP. Not only that, it will also remove any disablePictureInPicture attributes (merging my userscript into the extension).
> > So new version should remove feature-policy headers, permissions policy headers, the disablePictureInPicture attribute, and allow for basic PiP toggle. Hopefully that takes care of most use cases.
> 
> Beautiful. I'll let you know how it works when it's live on edge!

Working like a charm. TY!

**Comment by polywock** [comment]
Great to hear!
